### ISSUE TITLE
inference 2.5D model bug

### ISSUE THREAD

**Issue by JohannaRahm** [czbiohub/microDL#138] opened 2022-02-17 19:31 UTC
Hi, running inference with a 2.5D model results in an error related to the dimensions of the pred_stack (and target_stack) variable at infernce->image_inference.py->predict_2d(). A 2D model yields stacks in the format (ZCYX), which can be transposed to (CYXZ) in the predict_2d function. A 2.5D model yields stacks in the format (ZC?YX), which leads to the dimensionality error. I also attached an image of the preprocessing 2.5D model single channel, to show that 2D tiles were correctly configured.

**Paths to used configs**
- 2.5D model single channel: /gpfs/CompMicro/software/configfiles/Johanna/micro_DL_copy/tests/config_inference_2021_04_20_HEK_OC43_widefield_pool_25UNet_DAPI_5.yml
- 2.5D model multi channel: gpfs/CompMicro/software/configfiles/Johanna/micro_DL_copy/tests/config_inference_2021_04_20_HEK_OC43_widefield_pool_25UNet_DAPI_MTub_5.yml
- 2D model single channel: /gpfs/CompMicro/software/configfiles/Johanna/micro_DL_copy/tests/2D_model/config_inference_2021_04_20_HEK_OC43_widefield_M1_DAPI.yml

**Error message**
<img width="918" alt="image" src="https://user-images.githubusercontent.com/48733135/154553480-c1fbdfe8-e199-4728-ba4b-504d886a5183.png">
**Preprocessing config of 2.5D model single channel**
![image](https://user-images.githubusercontent.com/48733135/154555135-2588ac81-9eff-4ac7-9b74-70cf12174e27.png)

**Comment by smguo** [comment] 2022-02-17 21:53
Thanks for the detailed description of the issue @JohannaRahm! A few suggestions for future issues: It would be great to also specify the branch you're running (e.g. `dl_mbl_2020` in this case). Also it's better to paste the command you ran instead of the screen shot so others can reproduce the error and debug more easily.   

The error is due to the output of 2.5D model has shape (b, c, z, y, x) with z=1, while 2D model output has shape (b, c, y, x). I'll leave my suggestion in #139

**Comment by smguo** [comment] 2022-02-17 23:21
Fixed in #139. Closing it.

**Closed by smguo** 2022-02-17 23:21 UTC
